### ISSUE TITLE
styled-components 라이브러리 추가

### ISSUE THREAD

**Issue by aajy** [Jangwoohyeok123/Economic-Context#121]
## 목적
>  css 와 컴포넌트의 맵핑을 쉽게 만들기 위해 라이브러리를 적용.
## 내용 
- [ ] 컴포넌트 스타일링을 한 파일 내에서 작업할 수 있습니다.
- [ ] styled-components 의 문법을 사용하여 코드량을 줄일 수 있습니다.
- [ ] styled-components 라이브러리를 사용하면 반응형관련 javascript 상태값을 스타일링에 적용할 수있습니다.

**Comment by Jangwoohyeok123** [comment]
목적이 css 와 컴포넌트의 맵핑을 쉽게 만들기 위해 라이브러리를 적용했다고 말하는게 적절해보입니다.
