### ISSUE TITLE
Styled-component 컨벤션

### ISSUE THREAD

**Issue by Jangwoohyeok123** [Jangwoohyeok123/Economic-Context#135]
## 목적
> 기존 컴포넌트와 Styled-component간의 이름이 겹치는 경우
## 내용 
- [ ] 컴포넌트 이름과 컴포넌트의 최상위 요소의 컴포넌트이름과 class 이름이 같은 경우에 처리에 문제가 있습니다.
## 참고사항
https://velog.io/@hayoung474/Front-End-%EB%B3%B5%EC%9E%A1%ED%95%9C-styled-components-%EA%B5%AC%EC%A1%B0-%EA%B0%9C%EC%84%A0%ED%95%B4%EB%B3%B4%EA%B8%B0

**Comment by aajy** [comment]
[관련 wiki](https://github.com/Jangwoohyeok123/Economic-Context/wiki/styled%E2%80%90component-Convention--&-%EC%82%AC%EC%9A%A9-%EB%B0%A9%EB%B2%95)
