### ISSUE TITLE
MyContext id값 상이하게 요청되는 현상

### ISSUE THREAD

**Issue by aajy** [Jangwoohyeok123/Economic-Context#36]
## 목적
> context페이지 데이터 요청 로직 수정 필요합니다.
### 상황1
-  `http://localhost:4000/context/user/1` 로 받는 response  data와 상이한 id값으로 요청됩니다.
-  `http://localhost:4000/context/user/1`의 response  
: `[
    {
        "id": 1,
        "name": "first",
       ...생략...
    },
    {
        "id": 2,
        "name": "second",
        ...생략...
    }
]`
"first"의 id값인 1이 아닌 2로 요청되어(`http://localhost:4000/context/2`) 상이한 데이터가 불러와짐

### 상황2
-  `http://localhost:4000/context/user/1`의 response  
: ` [
    {
        "id": 1,
        "name": "first",
      ...생략...
    },
    {
        "id": 2,
        "name": "second",
       ...생략...
    },
    {
        "id": 3,
        "name": "abcdefghijklmnopqrstuvwxyzaaaaaaaa",
      ...생략...
    },
    {
        "id": 4,
        "name": "abcdefghijklmnopqrstuvwxyzaaaaaaaa",
     ...생략...
    },
    {
        "id": 5,
        "name": "abcdefghijklmnopqrstuvwxyzaaaaaaaa",
       ...생략...
    }
]`
일 때,
![image](https://github.com/Jangwoohyeok123/Economic-Context/assets/70941333/36354079-5293-4a90-a6fe-7d8f8baaaec8)
위 이미지처럼 하나의 context로 선택 되어 활성화되고, `http://localhost:4000/context/3 요청이 한 번 이뤄집니다.
## 참고사항

**Comment by Jangwoohyeok123** [comment]
음... 혹시 context 이름이 모두 같을 때 생기는 현상인가요 ?

**Comment by aajy** [comment]
> 음... 혹시 context 이름이 모두 같을 때 생기는 현상인가요 ?

context 이름이 같을 때를 특정하지 않고,
각 context를 선택했을 때 동일하게 상이한 id로 요청됩니다.

**Comment by Jangwoohyeok123** [comment]
state 의 변경과 qeuryKey 의 변경이 동기화 돼야하는데 state 변경 후 useEffect 를 활용하면 state 와 queryKey 의 동기화가 깨지는 현상을 해결함
