### ISSUE TITLE
Menu컴포넌트의 MyContext하단 isAccordianOpen이 불규칙적으로 false가 되는 에러

### ISSUE THREAD

**Issue by aajy** [Jangwoohyeok123/Economic-Context#49]
## 목적
> Allcontext 페이지에서 개별 context로 이동 시
 Menu컴포넌트의 MyContextTab의 하단 아코디언 메뉴(isAccordianOpen)는 항상 열려(true)있어야 한다.

## 내용 
>Allcontext페이지에는 context의 리스트가 있는데, context를 클릭 하면 해당 context 개별페이지로 이동이 된다.
개별 context페이지로 이동하면서 활성화된 `context의 name`이 아코디언메뉴에 활성화된 상태로 보여진다.

- 근데 이때 아코디언 메뉴가 열리지 않는 에러 발생.

## 참고사항
>MyContextTab페이지에 해당하는 개별 context페이지임에도 MyContext의 아코디언이 닫혀있는 이미지.

![image](https://github.com/Jangwoohyeok123/Economic-Context/assets/70941333/a0a44343-1529-492e-9681-b6bea0a67cb6)

- [ ] 아코디언메뉴의 노출을 제어하는 isAccordianOpen 상태를 처리하는 로직확인이 필요하다.

**Comment by Jangwoohyeok123** [comment]
저번보다 이해가 잘되네요. 수고하셨습니다!
