### ISSUE TITLE
AllContext페이지에서 Indicators로 이동할 때 react-paginate 경고 발생하는 현상

### ISSUE THREAD

**Issue by aajy** [Jangwoohyeok123/Economic-Context#50]
## 목적
> AllContext컴포넌트에서 IndicatorsTab페이지로 이동하는 버튼(Plus icon) 클릭 시 
IndicatorsTab페이지로 이동은 되지만, react-paginate 경고가 발생함.

## 내용 
- 에러내용
`(react-paginate): The forcePage prop provided is greater than the maximum page index from pageCount prop (0 > -1).`

- [ ] 페이지 이동에 관한 로직(src/page/index.tsx) 확인 필요

**Comment by Jangwoohyeok123** [comment]
커스텀 페이지네이션 컴포넌트를 제작했으며 라이브러리 자체에 결함이 있는듯합니다.
