### ISSUE TITLE
MyContextTab페이지에서 AllContext를 보여줄 때, context 정렬 수정필요

### ISSUE THREAD

**Issue by aajy** [Jangwoohyeok123/Economic-Context#51]
## 목적
> MyContextTab페이지에서 AllContext를 보여줄 때, 한 줄에 4개의 context가 고정으로 보여진다.

## 내용 
- 반응형 처리를 통해 해상도에 따른 media query설정으로 한 줄에 보여지는 context개수 조절(=context크기 조절)이 필요하다.

## 참고사항
![image](https://github.com/Jangwoohyeok123/Economic-Context/assets/70941333/62bf8e46-1c28-4117-8126-9040eb442c77)
![image](https://github.com/Jangwoohyeok123/Economic-Context/assets/70941333/0259bc6e-bd27-421c-b1fe-40de3357ca46)

**Comment by Jangwoohyeok123** [comment]
👋 수고하셨습니다.
